fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: no-commit-to-branch
        name: Check Commit on Protected Branch
      - id: end-of-file-fixer
        name: Add Newline at EOF
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (Python)
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Black
