name: Coverage
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
        virtualenvs-create: false
    - name: Install Project Dependencies
      run: poetry install --no-interaction --no-root
    - name: Generate Coverage Report
      run: coverage run -m unittest discover tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: tests
        fail_ci_if_error: true
